// Package api exposes Atrio's internal HTTP+JSON API, with SSE for real-time
// updates. It is the single surface consumed by both the CLI and the local web
// portal, which guarantees capability parity between the two interfaces and
// keeps business logic out of the frontend.
//
// Security rules: the server binds exclusively to localhost, requires a session
// token generated by the CLI, and exposes no destructive action over GET — which
// is what mitigates CSRF and DNS-rebinding against a local port.
//
// Dependency rule (ADR-016): api is a delivery layer, an entry point into the
// system rather than a building block, so no package of this module may import
// it — with one exception, cli, whose portal command starts the server.
//
// cmd/atrio therefore reaches api transitively through cli, but importing it
// directly is still a violation. The architecture test in internal/archtest
// checks direct imports and the transitive closure separately, which is what
// keeps those two cases distinguishable.
package api
